/** Build-time map of real logo files present in /public/clients (generated by scripts/sync-client-logos). */
export const CLIENT_LOGO_FILES: Record<string, string> = {
  "td-bank": "/clients/td-bank.png",
  "harvard-medtech": "/clients/harvard-medtech.png",
  "chatoor": "/clients/chatoor.png",
  "modelo": "/clients/modelo.png",
  "seattle-kraken": "/clients/seattle-kraken.png",
} as const;
